name: Ruff formater

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Ruff format with diff output
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --diff'
          version: 0.4.2
