name: Daily test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bleak
      - name: Test with pytest
        run: |
          pip install pytest
          tries=0
          until [ "$tries" -ge 5 ]
          do
            pytest && break
            exit_code=$?
            tries=$((tries+1))
            sleep 60
          done
          exit $exit_code